########################################################################
##### COPYRIGHT 2018 onwards - Sunit Katkar (sunitkatkar@gmail.com)
##### https://sunitkatkar.blogspot.com/ 
########################################################################
spring:
  thymeleaf:
    cache: false
    mode: HTML
  jpa:
    database: mysql
    show-sql: true 
    generate-ddl: false
    hibernate: 
      hbm2ddl-auto: update
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: trace   
        
##################################################################
# MULTITENANCY MASTER DATABASE SETUP
##################################################################        
multitenancy: 
  mtapp: 
    master: 
      datasource:
        url: jdbc:mysql://localhost:3306/masterdb?useSSL=false&serverTimezone=UTC
        username: root
        password: 
        driverClassName: com.mysql.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 10
        idleTimeout: 300000
        minIdle: 10
        poolName: masterdb-connection-pool

##################################################################
# LOGGING LEVELS
##################################################################        
logging:
  level:
    org:
      hibernate: 
        type:  
          descriptor: 
            sql: 
              BasicBinder: TRACE 
